//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolVeRProtected.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VolVeRProtected.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7scx {
            get {
                object obj = ResourceManager.GetObject("7scx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Class1
        ///{
        ///    internal class Class1
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Class1 {
            get {
                return ResourceManager.GetString("Class1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Class2
        ///{
        ///    internal class Class2
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Class2 {
            get {
                return ResourceManager.GetString("Class2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Protected
        ///{
        ///    internal class Class1
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Class3_____________________ {
            get {
                return ResourceManager.GetString("Class3_____________________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Class1343443
        ///{
        ///    internal class Class1343443
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Class343343343434 {
            get {
                return ResourceManager.GetString("Class343343343434", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Class1232
        ///{
        ///    internal class Class1232
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Class4_____________________________________ {
            get {
                return ResourceManager.GetString("Class4_____________________________________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Class121
        ///{
        ///    internal class Class121
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Class4645445 {
            get {
                return ResourceManager.GetString("Class4645445", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Protected
        ///{
        ///    internal class Class1488
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Class5__ {
            get {
                return ResourceManager.GetString("Class5__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Class7
        ///{
        ///    internal class Class7
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Class6____ {
            get {
                return ResourceManager.GetString("Class6____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Protected
        ///{
        ///    internal class Class13123
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Class7_________________________________________________________________ {
            get {
                return ResourceManager.GetString("Class7_________________________________________________________________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Class1223
        ///{
        ///    internal class Class1223
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Class7542 {
            get {
                return ResourceManager.GetString("Class7542", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Class8
        ///{
        ///    internal class Class1
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Class8 {
            get {
                return ResourceManager.GetString("Class8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_button {
            get {
                object obj = ResourceManager.GetObject("close-button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus_sign {
            get {
                object obj = ResourceManager.GetObject("minus-sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.ComponentModel;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Management;
        ///using System.Reflection;
        ///using System.Runtime.InteropServices;
        ///using System.Security;
        ///using System.Security.AccessControl;
        ///using System.Security.Cryptography;
        ///using System.Security.Principal;
        ///using System.Text;
        ///using System.Text.RegularExpressions;
        ///using System.Net;
        ///
        ///[assembly: AssemblyTitle(&quot;Installation Utility&quot;)]
        ///[assembly: AssemblyDescription(&quot;Microsoft .NET Services Installatio [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace VolVeR1
        ///{
        ///    internal class VolVeR1
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string VolVeR {
            get {
                return ResourceManager.GetString("VolVeR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace VolVeR
        ///{
        ///    internal class VolVeR
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string VolVeR____________________________________________1 {
            get {
                return ResourceManager.GetString("VolVeR____________________________________________1", resourceCulture);
            }
        }
    }
}
